sudo: required
dist: trusty
language: java

#skips default install - see script bellow
install: true

cache:
  directories:
    - $HOME/.m2

before_install:
  - wget https://archive.apache.org/dist/maven/maven-3/3.6.1/binaries/apache-maven-3.6.1-bin.zip
  - unzip -qq apache-maven-3.6.1-bin.zip
  - export M2_HOME=$PWD/apache-maven-3.6.1
  - export PATH=$M2_HOME/bin:$PATH
  - export MAVEN_OPTS='-Xmx6g'

# custom script is used so build and tests are done in one mvn command, separating it (as Travis does by default) leads to problem with ConnId (notably DummyResource)
script: mvn clean install

addons:
  hostname: localhost # workaround for short hostname

env:
  global:
    - MALLOC_ARENA_MAX=2

matrix:
  include:
    - name: JDK8 - Run all excluding model-intest
      script: mvn install -T 1C -q -DskipTests; mvn verify -DskipModelIntTest=true -DskipModelUnitTest=true -DtestsRetryCount=2
    - name: JDK8 - Run only model-intest
      script: mvn install -T 1C -q -DskipTests; travis_wait 120 mvn verify -pl :model-intest -DtestsRetryCount=2
